#ifndef __SOUNDS_H__
#define __SOUNDS_H__

typedef enum {
    SFX_ROCKET_PICKING_UP = 0x00,
    SFX_ROCKET_HOLDING = 0x01,
    SFX_ROCKET_LET_GO = 0x02,

    SFX_ROCKET_YIP = 0x04,
    SFX_ROCKET_LAND = 0x05,
    SFX_ROCKET_OW = 0x06,
    SFX_ROCKET_ENTER_VEHICLE = 0x07,
    SFX_ROCKET_EXIT_VEHICLE = 0x08,
    SFX_ROCKET_YEAH = 0x09,

    SFX_GET_TICKET = 0x0C,
    SFX_ROCKET_HOO = 0x0D,
    SFX_ROCKET_WHEE = 0x0E,
    SFX_ROCKET_WOOHOO = 0x0F,

    SFX_BUZZER = 0x21,

    SFX_PAUSE_CYCLE = 0x23,
    SFX_PAUSE_SELECT = 0x24,
    SFX_PAUSE_ENTER = 0x25,
    SFX_PAUSE_EXIT = 0x26,
    SFX_PAUSE_CONTROLS = 0x27,
    SFX_PAUSE_HINT = 0x28,
    SFX_CAMERA = 0x29,
    SFX_CAMERA_STUCK = 0x2A,

    SFX_BEE = 0x2C,

    SFX_GET_TOKEN_SILVER = 0x38,
    SFX_GET_TOKEN_GOLD = 0x39,
    SFX_GET_TOKEN_PURPLE = 0x3A,
    SFX_PAUSE_CYCLE2 = 0x3B, // The same as 0x23?
    SFX_PAUSE_SELECT2 = 0x3C, // The same as 0x24?

    SFX_CLOWN_HONK = 0x42,
    SFX_CLOWN_LAUGH = 0x43,
    SFX_CLOWN_WHISTLE = 0x44,
    SFX_CLOWN_OW = 0x45,

    SFX_SHEEP_BAA = 0x4A,
    SFX_SHEEP_YELL = 0x4B,

    SFX_ZAP = 0x4E,

    SFX_GAVIN_HMM1 = 0x54,

    SFX_PAINT_SHOOT = 0x56,
    SFX_PAINT_SPLAT = 0x57,
    SFX_CHICKEN_BUCKAW = 0x58,

    SFX_TROLL = 0x60,

    SFX_MUSHROOM_LAUGH = 0x65,
    SFX_MUSHROOM_WAH = 0x66,

    SFX_ZAP2 = 0x68,

    SFX_FREEZE_RAY = 0x6D,

    SFX_GRAPPLE_AIM = 0x6F,
    SFX_GRAPPLE_SHOOT = 0x70,

    SFX_PISTON = 0x76,

    SFX_TINKER_HMM = 0x83,
    SFX_JOJO_LAUGH1 = 0x84,
    SFX_GAVIN_HMM2 = 0x85,

    SFX_WHOOPIE1 = 0x88,
    SFX_WHOOPIE2 = 0x89,
    SFX_TINKER_WORKING = 0x8A,

    SFX_ROCKET_DEATH = 0x8F,
    SFX_ROCKET_HIT1 = 0x90,
    SFX_ROCKET_HIT2 = 0x91,

    SFX_CHICKEN_CLUCK = 0x98,

    SFX_JOJO_LAUGH2 = 0x9B,
    SFX_GAVIN_HMM3 = 0x9C,
    SFX_GAVIN_HMM4 = 0x9D,
    SFX_JOJO_SQUEAL = 0x9E,

    SFX_WARP_EXIT = 0xA0,
    SFX_WARP_ENTER = 0xA1,







} soundId_t;

#endif
